### ISSUE TITLE
Height to Wrap Content not Fixed.

### ISSUE THREAD

**Issue by vipinnegi90** [RitickSaha/glassmorphism#1]
Thanks for this amazing package :) By the way, Is it possible not to provide height explicitly but take the content height?

**Comment by RitickSaha** [comment]
Hmm.. Till now We used tp get it done with Providing a fixed hight for the Custom painter and that worked fine. 

If you could show me the screenshot and give me the code to recreate the Bug/suggestion it will be a great head shart on to your request.

**Comment by vipinnegi90** [comment]
Yes, no doubt that it works just great. 
My use-case is I need to fill a container with dynamic data and the height will differ on different content set. Providing a fixed height will cause bottom overflow-error if the content is large and requires more height than the provided one.
I hope this will help to understand the case.

**Comment by RitickSaha** [comment]
> Yes, no doubt that it works just great. 
> Actually, my case is quite simple. I just want to use this effect on a Container with dynamic data and the height will differ for every user. Providing a fixed height will cause a bottom-overflow error if the content is large and requires more height than the provided one.
> I hope this will help to understand the case. 

Ok.. I will update the package as soon as i can.. Do you want to contribute to it?

**Comment by vipinnegi90** [comment]
Thank you for asking. I wish I could contribute with you to it and I'd be more than happy doing that, but I am not as skilled enough at the moment. I am only good for Designing UI level :(

**Comment by RitickSaha** [comment]
> Thank you for asking. I wish I could contribute with you to it and I'd be more than happy doing that, but I am not as skilled enough at the moment. I am only good for Designing UI level :(

Ohh you have the opportunity to learn something. Will guide you. If something goes bad then I will take over.

**Comment by RitickSaha** [comment]
Hello, 
I tried every possible solution to make use of the child widget's Size Dimensions. But as Glassmorphic Effect requires custom painted to create glass rays the size Metric is required before the Widget gets render. Which makes it harder to Render after the child gets rendered. as flutter renders the parent widget first and then the child because of that using Child to set the height of the parent widget is not possible. 

You can make use of GlobalKey In Glassmorphic package to set the height after your Dynamic child gets rendered and then change the Dimensions of the Parent widget. Or rather use the MediaQuery to fix the height of the child and the parent widget to make it responsive and avoid overflow errors.

**Comment by RitickSaha** [comment]
I am closing this issue... You can re-open anytime if you want.
